language: node_js
node_js:
 - "6.11.5"
script:
 - echo "Deploying"
 - mkdir ../public
 - cp -r * ../public
 - mv ../public public
install:
 - npm install -g firebase-tools
after_success:
 - firebase deploy --token $FIREBASE_TOKEN
